[package]
name = "rbxlk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.33.0", features = ["rt-multi-thread"] }
poise = "0.5.6"
dotenv = "0.15.0"