services:
  rbxlk:
    build:
      context: .
      target: rbxlk
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://rbxlk:mypassword@postgres/rbxlk

  cron:
    build:
      context: .
      target: cron
    restart: always
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://rbxlk:mypassword@postgres/rbxlk
    
  web:
    build:
      context: .
      target: web
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://rbxlk:mypassword@postgres/rbxlk
    ports:
      - '8080:8080'

  postgres:
    image: postgres
    restart: always
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: rbxlk
      POSTGRES_USER: rbxlk
      POSTGRES_PASSWORD: mypassword
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.pam
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
  postgres_storage: {}