CREATE TABLE verif (
    discord_id BIGINT PRIMARY KEY NOT NULL UNIQUE,
    roblox_id BIGINT NOT NULL UNIQUE,
    string VARCHAR NOT NULL,
    start_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)